[project]
name = "postgress-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faiss-cpu>=1.8.0",
    "langchain>=0.3.0",
    "langchain-community>=0.3.0",
    "langchain-core>=0.3.0",
    "langchain-openai>=0.2.0",
    "langchain-text-splitters>=0.3.0",
    "psycopg2-binary>=2.9.9",
    "pytest>=8.3.3",
    "python-dotenv>=1.0.1",
    "sqlalchemy>=2.0.35",
    "streamlit>=1.38.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.mutmut]
paths_to_mutate = ["rag_core.py"]
tests_dir = "tests/"
runner = "python -m pytest -x"
