sonar.projectKey=postgress-rag
sonar.projectName=Postgress-RAG
sonar.sources=.
sonar.tests=tests
sonar.exclusions=.venv/**,tests/**,coverage-html/**,mutation-report/**,dependency-check-report/**,__pycache__/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results/junit.xml
sonar.sourceEncoding=UTF-8
