sonar.projectKey=postgress-rag
sonar.projectName=Postgress-RAG
sonar.sources=.
sonar.exclusions=.venv/**,tests/**,html/**,dependency-check-report/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results/junit.xml
sonar.sourceEncoding=UTF-8
